데코레이터 패턴(Decorator Pattern)
Team-ITDA/studyhub pull request #38
Opened 2020-11-12 06:53 UTC by Hyung1Jung

디자인 패턴(DesignPattern)의 일부 데코레이터 패턴(Decorator Pattern) 관해 학습한 내용을 바탕으로 작성합니다.

2020-11-12 07:26 UTC, Hyung1Jung commented
Spring이 왜 Spring인지? 와 SpringBoot VS Spring의 차이점을 구체적인 예를 들어 작성

2020-11-12 07:50 UTC, 1eehyeji approved these changes

2020-11-12 12:13 UTC, DunDung approved these changes
잘 읽었슴니다 💯 
데코레이터 패턴은 이해가 잘 안되네요 ㅠㅠㅠ
설명 추가해주시면 좋을듯 !!!

2020-11-12 12:13 UTC, DunDung commented on design pattern/Decorator Pattern/readme.md
> +![데코레이터 구조](https://user-images.githubusercontent.com/43127088/98900918-1e124280-24f6-11eb-8515-a5cffc919eb3.jpg)
아스팔트 위에서 그린건가요???

2020-11-12 12:13 UTC, DunDung commented on spring/Spring VS SpringBoot/readme.md
> +또 스프링 부트는 톰캣이 내장되어 있다. 이건 서버 구동 시간이 절반 가까이 단축된다.
내장 톰캣이면 왜?? 어떻게?? 서버 구동시간이 절반 가까이 단축되는 지 궁금함니다 !

2020-11-12 12:38 UTC, meeansub commented on spring/Spring VS SpringBoot/readme.md
> +```
들여쓰기 수정해주세요~

2020-11-12 12:38 UTC, meeansub commented on design pattern/Decorator Pattern/readme.md
> +![데코레이터 구조](https://user-images.githubusercontent.com/43127088/98900918-1e124280-24f6-11eb-8515-a5cffc919eb3.jpg)
그림판이나 [drawio](https://app.diagrams.net/)를 활용해서 깔끔하게 해주실 수 있나요??

2020-11-12 14:04 UTC, Hyung1Jung commented on design pattern/Decorator Pattern/readme.md
> +![데코레이터 구조](https://user-images.githubusercontent.com/43127088/98900918-1e124280-24f6-11eb-8515-a5cffc919eb3.jpg)
수정 완료 했습니다!

2020-11-13 01:49 UTC, zeroGone requested changes
예시 코드에 java 라고 명시 하면 가독성이 좋아집니다 수정 부탁드려요

```java
public void java();
```

2020-11-13 04:35 UTC, ROMANIAPEOPLE approved these changes

2020-11-13 10:23 UTC, hyeyeon2964 approved these changes

2020-11-13 12:14 UTC, meeansub approved these changes

2020-11-13 18:04 UTC, merged