REST API의 장단점에 대해 수정했습니다
Team-ITDA/studyhub pull request #44
Opened 2020-11-14 03:25 UTC by meeansub

REST API의 장단점에 대해 수정했습니다

[보러가기](https://github.com/Team-ITDA/studyhub/tree/minsub/web/REST)

2020-11-15 01:49 UTC, zeroGone commented on web/REST/README.md
> +###용어 정리
띄어쓰기요!!

2020-11-15 01:49 UTC, zeroGone requested changes
254번째 줄 깨졌습니다~~

2020-11-15 04:27 UTC, meeansub commented
> 254번째 줄 깨졌습니다~~

수정했습니다~

2020-11-15 10:36 UTC, hyeyeon2964 approved these changes

2020-11-15 14:30 UTC, DunDung approved these changes
굿굿

2020-11-15 23:32 UTC, Hyung1Jung approved these changes
잘 봤습니다.

2020-11-16 02:33 UTC, zeroGone approved these changes

2020-11-16 13:32 UTC, 1eehyeji approved these changes

2020-11-16 14:02 UTC, merged