feat : IntelliJ JSON Fragment Edit 기능
Team-ITDA/studyhub pull request #60
Opened 2020-12-07 14:53 UTC by Hyung1Jung

소소한 팁... 공유 합니다.

2020-12-08 06:00 UTC, zeroGone requested changes
spring 폴더 말고 intellij 폴더로 이동부탁드립니다 :)

2020-12-08 06:02 UTC, zeroGone commented
그리고 예제를 보니 <code>ObjectMapper</code> 의 <code>writeValueAsString</code> 메소드 쓰면 되지 않을까요??

2020-12-08 09:11 UTC, Hyung1Jung commented
> 그리고 예제를 보니 `ObjectMapper` 의 `writeValueAsString` 메소드 쓰면 되지 않을까요??
폴더 이동 완료하였습니다.   `ObjectMapper` 의 `writeValueAsString`에 관해 알아보니 제가 올렸던 사진의 예제에는 `writeValueAsString'를 쓰는게 더 효율적이겠군요! 리팩토링 하기 전, 그냥 단순 JSON 문자열 쉽게 만들기에 관해 올렸습니다ㅎㅎ

2020-12-08 12:56 UTC, hyeyeon2964 approved these changes

2020-12-09 03:14 UTC, zeroGone approved these changes

2020-12-09 04:53 UTC, meeansub approved these changes
팁 얻어 갑니다~

2020-12-09 06:32 UTC, JinminYANG commented
확인했습니다~

2020-12-09 06:33 UTC, JinminYANG approved these changes

2020-12-09 10:33 UTC, DunDung approved these changes
오오 굿정보네요. 저도 이거 굉장히 귀찮았었는데...
좋은 정보 감사합니다 👍

2020-12-10 03:50 UTC, 1eehyeji approved these changes
좋은 정보 감사합니다~~~~

2020-12-10 08:46 UTC, ROMANIAPEOPLE approved these changes

2020-12-10 09:04 UTC, merged